@extends('layouts.app')
@section('content')
    @if(Auth::check())
        @include('page-partials.dashboard')
    @endif
    @if(!Auth::check())
        @include('page-partials.register')
    @endif
@endsection
